<?php

//Constantes tipo de usuarios

define('TIPO_USER_ROOT','TU01');
define('TIPO_USER_ADMIN','TU02');
define('TIPO_USER_PROFESOR','TU03');
define('TIPO_USER_ESTUDIANTE','TU04');
define('TIPO_USER_ALMACENISTA','TU05');
define('TIPO_USER_SUPERVISOR','TU06');


//Comentado los permisos
//Constantes tipo de usuarios

define('PERMISO_CREAR_USUARIO','TPCU1');
define('PERMISO_MODIFICAR_USUARIO','TPMU2');
define('PERMISO_ELIMINAR_USUARIO','TPEU3');
define('PERMISO_CREAR_INVENTARIO','TPCI1');
define('PERMISO_MODIFICAR_INVENTARIO','TPMI2');
define('PERMISO_REGISTRAR_OBJETO','TPRO1');
define('PERMISO_MODIFICR_OBJETO','TPMO2');
define('PERMISO_ELIMINAR_OBJETO','TPEO3');
define('PERMISO_REGISTRAR_ELEMENTO','TPRE1');
define('PERMISO_MODIFICAR_ELEMENTO','TPME2');
define('PERMISO_ELIMINAR_ELEMENTO','TPME3');
define('PERMISO_REGISTRAR_CATALOGO','TPRC1');
define('PERMISO_MODIFICAR_CATALOGO','TPMC2');
define('PERMISO_ELIMINAR_CATALOGO','TPEC3');
define('PERMISO_REGISTRAR_ALMACEN','TPRA1');
define('PERMISO_MODIFICAR_ALMACEN','TPMA2');
define('PERMISO_ELIMINAR_ALMACEN','TPEA3');
define('PERMISO_REGISTRAR_LABORATORIO','TPRL1');
define('PERMISO_MODIFICAR_LABORATORIO','TPRL2');
define('PERMISO_ELIMINAR_LABORATORIO','TPRL3');

//Permisos Genericos

define('PERMISO_GENERICO_USUARIO', 'TPGU1');
define('PERMISO_GENERICO_CATALOGO', 'TPGC2');
define('PERMISO_GENERICO_INVENTARIO', 'TPGI3');
define('PERMISO_GENERICO_LABORATORIO', 'TPGL3');

//sexo

define('SEXO_MASCULINO', 10);
define('SEXO_FEMENINO', 20);

/// PATH
define('PATH_IMAGENES','/uploads/imagenes/');
define('PATH_AVATAR_MASCULINO', '/img/masculino.jpg');
define('PATH_AVATAR_FEMENINO', '/img/femenino.jpg');
define('PATH_NO_AVATAR', '/img/no-avatar.png');
define('PATH_ARCHIVOS_SQL', app_path()."/database/archivos_sql");

//NOMENCLATURAS

define('CODIGO_TIPO_USUARIO','TU');
define('CODIGO_PERMISO','PU');
define('CODIGO_ALMACEN','AL');
define('CODIGO_LABORATORIO', 'LA');
//define('CODIGO_AGRUPACION','');
define('CODIGO_PROVEEDORES', 'PRV');


//Tipos de moviemientos
define('MOV01', 'ENTRADA POR PROVEEDOR');
define('MOV02', 'ENTRADA POR DONACION');
define('MOV03', 'SALIDA POR PEDIDO');
define('MOV04', 'RETENIDO STOCK');
define('MOV05', 'RETENIDO POR PEDIDO');


//Condiciones para ordenes
define('ORDEN_ACTIVA', 'C01');
define('ORDEN_PENDIENTE', 'C02');
define('ORDEN_CANCELADA', 'C03');
define('ORDEN_COMPLETADA', 'C04');
define('DISPONIBLE', 'C05');
define('NO DISPONIBLE', 'C06');
define('RETENIDO', 'C07');


