<?php

class MunicipiosTableSeeder extends Seeder {


    public function run()
    {
       	DB::table('municipios')->delete();

       	$municipios = array(
		  array('id_municipio' => '1','id_estado' => '1','municipio' => 'Alto Orinoco'),
		  array('id_municipio' => '2','id_estado' => '1','municipio' => 'Atabapo'),
		  array('id_municipio' => '3','id_estado' => '1','municipio' => 'Atures'),
		  array('id_municipio' => '4','id_estado' => '1','municipio' => 'Autana'),
		  array('id_municipio' => '5','id_estado' => '1','municipio' => 'Manapiare'),
		  array('id_municipio' => '6','id_estado' => '1','municipio' => 'Maroa'),
		  array('id_municipio' => '7','id_estado' => '1','municipio' => 'Río Negro'),
		  array('id_municipio' => '8','id_estado' => '2','municipio' => 'Anaco'),
		  array('id_municipio' => '9','id_estado' => '2','municipio' => 'Aragua'),
		  array('id_municipio' => '10','id_estado' => '2','municipio' => 'Manuel Ezequiel Bruzual'),
		  array('id_municipio' => '11','id_estado' => '2','municipio' => 'Diego Bautista Urbaneja'),
		  array('id_municipio' => '12','id_estado' => '2','municipio' => 'Fernando Peñalver'),
		  array('id_municipio' => '13','id_estado' => '2','municipio' => 'Francisco Del Carmen Carvajal'),
		  array('id_municipio' => '14','id_estado' => '2','municipio' => 'General Sir Arthur McGregor'),
		  array('id_municipio' => '15','id_estado' => '2','municipio' => 'Guanta'),
		  array('id_municipio' => '16','id_estado' => '2','municipio' => 'Independencia'),
		  array('id_municipio' => '17','id_estado' => '2','municipio' => 'José Gregorio Monagas'),
		  array('id_municipio' => '18','id_estado' => '2','municipio' => 'Juan Antonio Sotillo'),
		  array('id_municipio' => '19','id_estado' => '2','municipio' => 'Juan Manuel Cajigal'),
		  array('id_municipio' => '20','id_estado' => '2','municipio' => 'Libertad'),
		  array('id_municipio' => '21','id_estado' => '2','municipio' => 'Francisco de Miranda'),
		  array('id_municipio' => '22','id_estado' => '2','municipio' => 'Pedro María Freites'),
		  array('id_municipio' => '23','id_estado' => '2','municipio' => 'Píritu'),
		  array('id_municipio' => '24','id_estado' => '2','municipio' => 'San José de Guanipa'),
		  array('id_municipio' => '25','id_estado' => '2','municipio' => 'San Juan de Capistrano'),
		  array('id_municipio' => '26','id_estado' => '2','municipio' => 'Santa Ana'),
		  array('id_municipio' => '27','id_estado' => '2','municipio' => 'Simón Bolívar'),
		  array('id_municipio' => '28','id_estado' => '2','municipio' => 'Simón Rodríguez'),
		  array('id_municipio' => '29','id_estado' => '3','municipio' => 'Achaguas'),
		  array('id_municipio' => '30','id_estado' => '3','municipio' => 'Biruaca'),
		  array('id_municipio' => '31','id_estado' => '3','municipio' => 'Muñóz'),
		  array('id_municipio' => '32','id_estado' => '3','municipio' => 'Páez'),
		  array('id_municipio' => '33','id_estado' => '3','municipio' => 'Pedro Camejo'),
		  array('id_municipio' => '34','id_estado' => '3','municipio' => 'Rómulo Gallegos'),
		  array('id_municipio' => '35','id_estado' => '3','municipio' => 'San Fernando'),
		  array('id_municipio' => '36','id_estado' => '4','municipio' => 'Atanasio Girardot'),
		  array('id_municipio' => '37','id_estado' => '4','municipio' => 'Bolívar'),
		  array('id_municipio' => '38','id_estado' => '4','municipio' => 'Camatagua'),
		  array('id_municipio' => '39','id_estado' => '4','municipio' => 'Francisco Linares Alcántara'),
		  array('id_municipio' => '40','id_estado' => '4','municipio' => 'José Ángel Lamas'),
		  array('id_municipio' => '41','id_estado' => '4','municipio' => 'José Félix Ribas'),
		  array('id_municipio' => '42','id_estado' => '4','municipio' => 'José Rafael Revenga'),
		  array('id_municipio' => '43','id_estado' => '4','municipio' => 'Libertador'),
		  array('id_municipio' => '44','id_estado' => '4','municipio' => 'Mario Briceño Iragorry'),
		  array('id_municipio' => '45','id_estado' => '4','municipio' => 'Ocumare de la Costa de Oro'),
		  array('id_municipio' => '46','id_estado' => '4','municipio' => 'San Casimiro'),
		  array('id_municipio' => '47','id_estado' => '4','municipio' => 'San Sebastián'),
		  array('id_municipio' => '48','id_estado' => '4','municipio' => 'Santiago Mariño'),
		  array('id_municipio' => '49','id_estado' => '4','municipio' => 'Santos Michelena'),
		  array('id_municipio' => '50','id_estado' => '4','municipio' => 'Sucre'),
		  array('id_municipio' => '51','id_estado' => '4','municipio' => 'Tovar'),
		  array('id_municipio' => '52','id_estado' => '4','municipio' => 'Urdaneta'),
		  array('id_municipio' => '53','id_estado' => '4','municipio' => 'Zamora'),
		  array('id_municipio' => '54','id_estado' => '5','municipio' => 'Alberto Arvelo Torrealba'),
		  array('id_municipio' => '55','id_estado' => '5','municipio' => 'Andrés Eloy Blanco'),
		  array('id_municipio' => '56','id_estado' => '5','municipio' => 'Antonio José de Sucre'),
		  array('id_municipio' => '57','id_estado' => '5','municipio' => 'Arismendi'),
		  array('id_municipio' => '58','id_estado' => '5','municipio' => 'Barinas'),
		  array('id_municipio' => '59','id_estado' => '5','municipio' => 'Bolívar'),
		  array('id_municipio' => '60','id_estado' => '5','municipio' => 'Cruz Paredes'),
		  array('id_municipio' => '61','id_estado' => '5','municipio' => 'Ezequiel Zamora'),
		  array('id_municipio' => '62','id_estado' => '5','municipio' => 'Obispos'),
		  array('id_municipio' => '63','id_estado' => '5','municipio' => 'Pedraza'),
		  array('id_municipio' => '64','id_estado' => '5','municipio' => 'Rojas'),
		  array('id_municipio' => '65','id_estado' => '5','municipio' => 'Sosa'),
		  array('id_municipio' => '66','id_estado' => '6','municipio' => 'Caroní'),
		  array('id_municipio' => '67','id_estado' => '6','municipio' => 'Cedeño'),
		  array('id_municipio' => '68','id_estado' => '6','municipio' => 'El Callao'),
		  array('id_municipio' => '69','id_estado' => '6','municipio' => 'Gran Sabana'),
		  array('id_municipio' => '70','id_estado' => '6','municipio' => 'Heres'),
		  array('id_municipio' => '71','id_estado' => '6','municipio' => 'Piar'),
		  array('id_municipio' => '72','id_estado' => '6','municipio' => 'Angostura (Raúl Leoni)'),
		  array('id_municipio' => '73','id_estado' => '6','municipio' => 'Roscio'),
		  array('id_municipio' => '74','id_estado' => '6','municipio' => 'Sifontes'),
		  array('id_municipio' => '75','id_estado' => '6','municipio' => 'Sucre'),
		  array('id_municipio' => '76','id_estado' => '6','municipio' => 'Padre Pedro Chien'),
		  array('id_municipio' => '77','id_estado' => '7','municipio' => 'Bejuma'),
		  array('id_municipio' => '78','id_estado' => '7','municipio' => 'Carlos Arvelo'),
		  array('id_municipio' => '79','id_estado' => '7','municipio' => 'Diego Ibarra'),
		  array('id_municipio' => '80','id_estado' => '7','municipio' => 'Guacara'),
		  array('id_municipio' => '81','id_estado' => '7','municipio' => 'Juan José Mora'),
		  array('id_municipio' => '82','id_estado' => '7','municipio' => 'Libertador'),
		  array('id_municipio' => '83','id_estado' => '7','municipio' => 'Los Guayos'),
		  array('id_municipio' => '84','id_estado' => '7','municipio' => 'Miranda'),
		  array('id_municipio' => '85','id_estado' => '7','municipio' => 'Montalbán'),
		  array('id_municipio' => '86','id_estado' => '7','municipio' => 'Naguanagua'),
		  array('id_municipio' => '87','id_estado' => '7','municipio' => 'Puerto Cabello'),
		  array('id_municipio' => '88','id_estado' => '7','municipio' => 'San Diego'),
		  array('id_municipio' => '89','id_estado' => '7','municipio' => 'San Joaquín'),
		  array('id_municipio' => '90','id_estado' => '7','municipio' => 'Valencia'),
		  array('id_municipio' => '91','id_estado' => '8','municipio' => 'Anzoátegui'),
		  array('id_municipio' => '92','id_estado' => '8','municipio' => 'Tinaquillo'),
		  array('id_municipio' => '93','id_estado' => '8','municipio' => 'Girardot'),
		  array('id_municipio' => '94','id_estado' => '8','municipio' => 'Lima Blanco'),
		  array('id_municipio' => '95','id_estado' => '8','municipio' => 'Pao de San Juan Bautista'),
		  array('id_municipio' => '96','id_estado' => '8','municipio' => 'Ricaurte'),
		  array('id_municipio' => '97','id_estado' => '8','municipio' => 'Rómulo Gallegos'),
		  array('id_municipio' => '98','id_estado' => '8','municipio' => 'San Carlos'),
		  array('id_municipio' => '99','id_estado' => '8','municipio' => 'Tinaco'),
		  array('id_municipio' => '100','id_estado' => '9','municipio' => 'Antonio Díaz'),
		  array('id_municipio' => '101','id_estado' => '9','municipio' => 'Casacoima'),
		  array('id_municipio' => '102','id_estado' => '9','municipio' => 'Pedernales'),
		  array('id_municipio' => '103','id_estado' => '9','municipio' => 'Tucupita'),
		  array('id_municipio' => '104','id_estado' => '10','municipio' => 'Acosta'),
		  array('id_municipio' => '105','id_estado' => '10','municipio' => 'Bolívar'),
		  array('id_municipio' => '106','id_estado' => '10','municipio' => 'Buchivacoa'),
		  array('id_municipio' => '107','id_estado' => '10','municipio' => 'Cacique Manaure'),
		  array('id_municipio' => '108','id_estado' => '10','municipio' => 'Carirubana'),
		  array('id_municipio' => '109','id_estado' => '10','municipio' => 'Colina'),
		  array('id_municipio' => '110','id_estado' => '10','municipio' => 'Dabajuro'),
		  array('id_municipio' => '111','id_estado' => '10','municipio' => 'Democracia'),
		  array('id_municipio' => '112','id_estado' => '10','municipio' => 'Falcón'),
		  array('id_municipio' => '113','id_estado' => '10','municipio' => 'Federación'),
		  array('id_municipio' => '114','id_estado' => '10','municipio' => 'Jacura'),
		  array('id_municipio' => '115','id_estado' => '10','municipio' => 'José Laurencio Silva'),
		  array('id_municipio' => '116','id_estado' => '10','municipio' => 'Los Taques'),
		  array('id_municipio' => '117','id_estado' => '10','municipio' => 'Mauroa'),
		  array('id_municipio' => '118','id_estado' => '10','municipio' => 'Miranda'),
		  array('id_municipio' => '119','id_estado' => '10','municipio' => 'Monseñor Iturriza'),
		  array('id_municipio' => '120','id_estado' => '10','municipio' => 'Palmasola'),
		  array('id_municipio' => '121','id_estado' => '10','municipio' => 'Petit'),
		  array('id_municipio' => '122','id_estado' => '10','municipio' => 'Píritu'),
		  array('id_municipio' => '123','id_estado' => '10','municipio' => 'San Francisco'),
		  array('id_municipio' => '124','id_estado' => '10','municipio' => 'Sucre'),
		  array('id_municipio' => '125','id_estado' => '10','municipio' => 'Tocópero'),
		  array('id_municipio' => '126','id_estado' => '10','municipio' => 'Unión'),
		  array('id_municipio' => '127','id_estado' => '10','municipio' => 'Urumaco'),
		  array('id_municipio' => '128','id_estado' => '10','municipio' => 'Zamora'),
		  array('id_municipio' => '129','id_estado' => '11','municipio' => 'Camaguán'),
		  array('id_municipio' => '130','id_estado' => '11','municipio' => 'Chaguaramas'),
		  array('id_municipio' => '131','id_estado' => '11','municipio' => 'El Socorro'),
		  array('id_municipio' => '132','id_estado' => '11','municipio' => 'José Félix Ribas'),
		  array('id_municipio' => '133','id_estado' => '11','municipio' => 'José Tadeo Monagas'),
		  array('id_municipio' => '134','id_estado' => '11','municipio' => 'Juan Germán Roscio'),
		  array('id_municipio' => '135','id_estado' => '11','municipio' => 'Julián Mellado'),
		  array('id_municipio' => '136','id_estado' => '11','municipio' => 'Las Mercedes'),
		  array('id_municipio' => '137','id_estado' => '11','municipio' => 'Leonardo Infante'),
		  array('id_municipio' => '138','id_estado' => '11','municipio' => 'Pedro Zaraza'),
		  array('id_municipio' => '139','id_estado' => '11','municipio' => 'Ortíz'),
		  array('id_municipio' => '140','id_estado' => '11','municipio' => 'San Gerónimo de Guayabal'),
		  array('id_municipio' => '141','id_estado' => '11','municipio' => 'San José de Guaribe'),
		  array('id_municipio' => '142','id_estado' => '11','municipio' => 'Santa María de Ipire'),
		  array('id_municipio' => '143','id_estado' => '11','municipio' => 'Sebastián Francisco de Miranda'),
		  array('id_municipio' => '144','id_estado' => '12','municipio' => 'Andrés Eloy Blanco'),
		  array('id_municipio' => '145','id_estado' => '12','municipio' => 'Crespo'),
		  array('id_municipio' => '146','id_estado' => '12','municipio' => 'Iribarren'),
		  array('id_municipio' => '147','id_estado' => '12','municipio' => 'Jiménez'),
		  array('id_municipio' => '148','id_estado' => '12','municipio' => 'Morán'),
		  array('id_municipio' => '149','id_estado' => '12','municipio' => 'Palavecino'),
		  array('id_municipio' => '150','id_estado' => '12','municipio' => 'Simón Planas'),
		  array('id_municipio' => '151','id_estado' => '12','municipio' => 'Torres'),
		  array('id_municipio' => '152','id_estado' => '12','municipio' => 'Urdaneta'),
		  array('id_municipio' => '179','id_estado' => '13','municipio' => 'Alberto Adriani'),
		  array('id_municipio' => '180','id_estado' => '13','municipio' => 'Andrés Bello'),
		  array('id_municipio' => '181','id_estado' => '13','municipio' => 'Antonio Pinto Salinas'),
		  array('id_municipio' => '182','id_estado' => '13','municipio' => 'Aricagua'),
		  array('id_municipio' => '183','id_estado' => '13','municipio' => 'Arzobispo Chacón'),
		  array('id_municipio' => '184','id_estado' => '13','municipio' => 'Campo Elías'),
		  array('id_municipio' => '185','id_estado' => '13','municipio' => 'Caracciolo Parra Olmedo'),
		  array('id_municipio' => '186','id_estado' => '13','municipio' => 'Cardenal Quintero'),
		  array('id_municipio' => '187','id_estado' => '13','municipio' => 'Guaraque'),
		  array('id_municipio' => '188','id_estado' => '13','municipio' => 'Julio César Salas'),
		  array('id_municipio' => '189','id_estado' => '13','municipio' => 'Justo Briceño'),
		  array('id_municipio' => '190','id_estado' => '13','municipio' => 'Libertador'),
		  array('id_municipio' => '191','id_estado' => '13','municipio' => 'Miranda'),
		  array('id_municipio' => '192','id_estado' => '13','municipio' => 'Obispo Ramos de Lora'),
		  array('id_municipio' => '193','id_estado' => '13','municipio' => 'Padre Noguera'),
		  array('id_municipio' => '194','id_estado' => '13','municipio' => 'Pueblo Llano'),
		  array('id_municipio' => '195','id_estado' => '13','municipio' => 'Rangel'),
		  array('id_municipio' => '196','id_estado' => '13','municipio' => 'Rivas Dávila'),
		  array('id_municipio' => '197','id_estado' => '13','municipio' => 'Santos Marquina'),
		  array('id_municipio' => '198','id_estado' => '13','municipio' => 'Sucre'),
		  array('id_municipio' => '199','id_estado' => '13','municipio' => 'Tovar'),
		  array('id_municipio' => '200','id_estado' => '13','municipio' => 'Tulio Febres Cordero'),
		  array('id_municipio' => '201','id_estado' => '13','municipio' => 'Zea'),
		  array('id_municipio' => '223','id_estado' => '14','municipio' => 'Acevedo'),
		  array('id_municipio' => '224','id_estado' => '14','municipio' => 'Andrés Bello'),
		  array('id_municipio' => '225','id_estado' => '14','municipio' => 'Baruta'),
		  array('id_municipio' => '226','id_estado' => '14','municipio' => 'Brión'),
		  array('id_municipio' => '227','id_estado' => '14','municipio' => 'Buroz'),
		  array('id_municipio' => '228','id_estado' => '14','municipio' => 'Carrizal'),
		  array('id_municipio' => '229','id_estado' => '14','municipio' => 'Chacao'),
		  array('id_municipio' => '230','id_estado' => '14','municipio' => 'Cristóbal Rojas'),
		  array('id_municipio' => '231','id_estado' => '14','municipio' => 'El Hatillo'),
		  array('id_municipio' => '232','id_estado' => '14','municipio' => 'Guaicaipuro'),
		  array('id_municipio' => '233','id_estado' => '14','municipio' => 'Independencia'),
		  array('id_municipio' => '234','id_estado' => '14','municipio' => 'Lander'),
		  array('id_municipio' => '235','id_estado' => '14','municipio' => 'Los Salias'),
		  array('id_municipio' => '236','id_estado' => '14','municipio' => 'Páez'),
		  array('id_municipio' => '237','id_estado' => '14','municipio' => 'Paz Castillo'),
		  array('id_municipio' => '238','id_estado' => '14','municipio' => 'Pedro Gual'),
		  array('id_municipio' => '239','id_estado' => '14','municipio' => 'Plaza'),
		  array('id_municipio' => '240','id_estado' => '14','municipio' => 'Simón Bolívar'),
		  array('id_municipio' => '241','id_estado' => '14','municipio' => 'Sucre'),
		  array('id_municipio' => '242','id_estado' => '14','municipio' => 'Urdaneta'),
		  array('id_municipio' => '243','id_estado' => '14','municipio' => 'Zamora'),
		  array('id_municipio' => '258','id_estado' => '15','municipio' => 'Acosta'),
		  array('id_municipio' => '259','id_estado' => '15','municipio' => 'Aguasay'),
		  array('id_municipio' => '260','id_estado' => '15','municipio' => 'Bolívar'),
		  array('id_municipio' => '261','id_estado' => '15','municipio' => 'Caripe'),
		  array('id_municipio' => '262','id_estado' => '15','municipio' => 'Cedeño'),
		  array('id_municipio' => '263','id_estado' => '15','municipio' => 'Ezequiel Zamora'),
		  array('id_municipio' => '264','id_estado' => '15','municipio' => 'Libertador'),
		  array('id_municipio' => '265','id_estado' => '15','municipio' => 'Maturín'),
		  array('id_municipio' => '266','id_estado' => '15','municipio' => 'Piar'),
		  array('id_municipio' => '267','id_estado' => '15','municipio' => 'Punceres'),
		  array('id_municipio' => '268','id_estado' => '15','municipio' => 'Santa Bárbara'),
		  array('id_municipio' => '269','id_estado' => '15','municipio' => 'Sotillo'),
		  array('id_municipio' => '270','id_estado' => '15','municipio' => 'Uracoa'),
		  array('id_municipio' => '271','id_estado' => '16','municipio' => 'Antolín del Campo'),
		  array('id_municipio' => '272','id_estado' => '16','municipio' => 'Arismendi'),
		  array('id_municipio' => '273','id_estado' => '16','municipio' => 'García'),
		  array('id_municipio' => '274','id_estado' => '16','municipio' => 'Gómez'),
		  array('id_municipio' => '275','id_estado' => '16','municipio' => 'Maneiro'),
		  array('id_municipio' => '276','id_estado' => '16','municipio' => 'Marcano'),
		  array('id_municipio' => '277','id_estado' => '16','municipio' => 'Mariño'),
		  array('id_municipio' => '278','id_estado' => '16','municipio' => 'Península de Macanao'),
		  array('id_municipio' => '279','id_estado' => '16','municipio' => 'Tubores'),
		  array('id_municipio' => '280','id_estado' => '16','municipio' => 'Villalba'),
		  array('id_municipio' => '281','id_estado' => '16','municipio' => 'Díaz'),
		  array('id_municipio' => '282','id_estado' => '17','municipio' => 'Agua Blanca'),
		  array('id_municipio' => '283','id_estado' => '17','municipio' => 'Araure'),
		  array('id_municipio' => '284','id_estado' => '17','municipio' => 'Esteller'),
		  array('id_municipio' => '285','id_estado' => '17','municipio' => 'Guanare'),
		  array('id_municipio' => '286','id_estado' => '17','municipio' => 'Guanarito'),
		  array('id_municipio' => '287','id_estado' => '17','municipio' => 'Monseñor José Vicente de Unda'),
		  array('id_municipio' => '288','id_estado' => '17','municipio' => 'Ospino'),
		  array('id_municipio' => '289','id_estado' => '17','municipio' => 'Páez'),
		  array('id_municipio' => '290','id_estado' => '17','municipio' => 'Papelón'),
		  array('id_municipio' => '291','id_estado' => '17','municipio' => 'San Genaro de Boconoíto'),
		  array('id_municipio' => '292','id_estado' => '17','municipio' => 'San Rafael de Onoto'),
		  array('id_municipio' => '293','id_estado' => '17','municipio' => 'Santa Rosalía'),
		  array('id_municipio' => '294','id_estado' => '17','municipio' => 'Sucre'),
		  array('id_municipio' => '295','id_estado' => '17','municipio' => 'Turén'),
		  array('id_municipio' => '296','id_estado' => '18','municipio' => 'Andrés Eloy Blanco'),
		  array('id_municipio' => '297','id_estado' => '18','municipio' => 'Andrés Mata'),
		  array('id_municipio' => '298','id_estado' => '18','municipio' => 'Arismendi'),
		  array('id_municipio' => '299','id_estado' => '18','municipio' => 'Benítez'),
		  array('id_municipio' => '300','id_estado' => '18','municipio' => 'Bermúdez'),
		  array('id_municipio' => '301','id_estado' => '18','municipio' => 'Bolívar'),
		  array('id_municipio' => '302','id_estado' => '18','municipio' => 'Cajigal'),
		  array('id_municipio' => '303','id_estado' => '18','municipio' => 'Cruz Salmerón Acosta'),
		  array('id_municipio' => '304','id_estado' => '18','municipio' => 'Libertador'),
		  array('id_municipio' => '305','id_estado' => '18','municipio' => 'Mariño'),
		  array('id_municipio' => '306','id_estado' => '18','municipio' => 'Mejía'),
		  array('id_municipio' => '307','id_estado' => '18','municipio' => 'Montes'),
		  array('id_municipio' => '308','id_estado' => '18','municipio' => 'Ribero'),
		  array('id_municipio' => '309','id_estado' => '18','municipio' => 'Sucre'),
		  array('id_municipio' => '310','id_estado' => '18','municipio' => 'Valdéz'),
		  array('id_municipio' => '341','id_estado' => '19','municipio' => 'Andrés Bello'),
		  array('id_municipio' => '342','id_estado' => '19','municipio' => 'Antonio Rómulo Costa'),
		  array('id_municipio' => '343','id_estado' => '19','municipio' => 'Ayacucho'),
		  array('id_municipio' => '344','id_estado' => '19','municipio' => 'Bolívar'),
		  array('id_municipio' => '345','id_estado' => '19','municipio' => 'Cárdenas'),
		  array('id_municipio' => '346','id_estado' => '19','municipio' => 'Córdoba'),
		  array('id_municipio' => '347','id_estado' => '19','municipio' => 'Fernández Feo'),
		  array('id_municipio' => '348','id_estado' => '19','municipio' => 'Francisco de Miranda'),
		  array('id_municipio' => '349','id_estado' => '19','municipio' => 'García de Hevia'),
		  array('id_municipio' => '350','id_estado' => '19','municipio' => 'Guásimos'),
		  array('id_municipio' => '351','id_estado' => '19','municipio' => 'Independencia'),
		  array('id_municipio' => '352','id_estado' => '19','municipio' => 'Jáuregui'),
		  array('id_municipio' => '353','id_estado' => '19','municipio' => 'José María Vargas'),
		  array('id_municipio' => '354','id_estado' => '19','municipio' => 'Junín'),
		  array('id_municipio' => '355','id_estado' => '19','municipio' => 'Libertad'),
		  array('id_municipio' => '356','id_estado' => '19','municipio' => 'Libertador'),
		  array('id_municipio' => '357','id_estado' => '19','municipio' => 'Lobatera'),
		  array('id_municipio' => '358','id_estado' => '19','municipio' => 'Michelena'),
		  array('id_municipio' => '359','id_estado' => '19','municipio' => 'Panamericano'),
		  array('id_municipio' => '360','id_estado' => '19','municipio' => 'Pedro María Ureña'),
		  array('id_municipio' => '361','id_estado' => '19','municipio' => 'Rafael Urdaneta'),
		  array('id_municipio' => '362','id_estado' => '19','municipio' => 'Samuel Darío Maldonado'),
		  array('id_municipio' => '363','id_estado' => '19','municipio' => 'San Cristóbal'),
		  array('id_municipio' => '364','id_estado' => '19','municipio' => 'Seboruco'),
		  array('id_municipio' => '365','id_estado' => '19','municipio' => 'Simón Rodríguez'),
		  array('id_municipio' => '366','id_estado' => '19','municipio' => 'Sucre'),
		  array('id_municipio' => '367','id_estado' => '19','municipio' => 'Torbes'),
		  array('id_municipio' => '368','id_estado' => '19','municipio' => 'Uribante'),
		  array('id_municipio' => '369','id_estado' => '19','municipio' => 'San Judas Tadeo'),
		  array('id_municipio' => '370','id_estado' => '20','municipio' => 'Andrés Bello'),
		  array('id_municipio' => '371','id_estado' => '20','municipio' => 'Boconó'),
		  array('id_municipio' => '372','id_estado' => '20','municipio' => 'Bolívar'),
		  array('id_municipio' => '373','id_estado' => '20','municipio' => 'Candelaria'),
		  array('id_municipio' => '374','id_estado' => '20','municipio' => 'Carache'),
		  array('id_municipio' => '375','id_estado' => '20','municipio' => 'Escuque'),
		  array('id_municipio' => '376','id_estado' => '20','municipio' => 'José Felipe Márquez Cañizalez'),
		  array('id_municipio' => '377','id_estado' => '20','municipio' => 'Juan Vicente Campos Elías'),
		  array('id_municipio' => '378','id_estado' => '20','municipio' => 'La Ceiba'),
		  array('id_municipio' => '379','id_estado' => '20','municipio' => 'Miranda'),
		  array('id_municipio' => '380','id_estado' => '20','municipio' => 'Monte Carmelo'),
		  array('id_municipio' => '381','id_estado' => '20','municipio' => 'Motatán'),
		  array('id_municipio' => '382','id_estado' => '20','municipio' => 'Pampán'),
		  array('id_municipio' => '383','id_estado' => '20','municipio' => 'Pampanito'),
		  array('id_municipio' => '384','id_estado' => '20','municipio' => 'Rafael Rangel'),
		  array('id_municipio' => '385','id_estado' => '20','municipio' => 'San Rafael de Carvajal'),
		  array('id_municipio' => '386','id_estado' => '20','municipio' => 'Sucre'),
		  array('id_municipio' => '387','id_estado' => '20','municipio' => 'Trujillo'),
		  array('id_municipio' => '388','id_estado' => '20','municipio' => 'Urdaneta'),
		  array('id_municipio' => '389','id_estado' => '20','municipio' => 'Valera'),
		  array('id_municipio' => '390','id_estado' => '21','municipio' => 'Vargas'),
		  array('id_municipio' => '391','id_estado' => '22','municipio' => 'Arístides Bastidas'),
		  array('id_municipio' => '392','id_estado' => '22','municipio' => 'Bolívar'),
		  array('id_municipio' => '407','id_estado' => '22','municipio' => 'Bruzual'),
		  array('id_municipio' => '408','id_estado' => '22','municipio' => 'Cocorote'),
		  array('id_municipio' => '409','id_estado' => '22','municipio' => 'Independencia'),
		  array('id_municipio' => '410','id_estado' => '22','municipio' => 'José Antonio Páez'),
		  array('id_municipio' => '411','id_estado' => '22','municipio' => 'La Trinidad'),
		  array('id_municipio' => '412','id_estado' => '22','municipio' => 'Manuel Monge'),
		  array('id_municipio' => '413','id_estado' => '22','municipio' => 'Nirgua'),
		  array('id_municipio' => '414','id_estado' => '22','municipio' => 'Peña'),
		  array('id_municipio' => '415','id_estado' => '22','municipio' => 'San Felipe'),
		  array('id_municipio' => '416','id_estado' => '22','municipio' => 'Sucre'),
		  array('id_municipio' => '417','id_estado' => '22','municipio' => 'Urachiche'),
		  array('id_municipio' => '418','id_estado' => '22','municipio' => 'José Joaquín Veroes'),
		  array('id_municipio' => '441','id_estado' => '23','municipio' => 'Almirante Padilla'),
		  array('id_municipio' => '442','id_estado' => '23','municipio' => 'Baralt'),
		  array('id_municipio' => '443','id_estado' => '23','municipio' => 'Cabimas'),
		  array('id_municipio' => '444','id_estado' => '23','municipio' => 'Catatumbo'),
		  array('id_municipio' => '445','id_estado' => '23','municipio' => 'Colón'),
		  array('id_municipio' => '446','id_estado' => '23','municipio' => 'Francisco Javier Pulgar'),
		  array('id_municipio' => '447','id_estado' => '23','municipio' => 'Páez'),
		  array('id_municipio' => '448','id_estado' => '23','municipio' => 'Jesús Enrique Losada'),
		  array('id_municipio' => '449','id_estado' => '23','municipio' => 'Jesús María Semprún'),
		  array('id_municipio' => '450','id_estado' => '23','municipio' => 'La Cañada de Urdaneta'),
		  array('id_municipio' => '451','id_estado' => '23','municipio' => 'Lagunillas'),
		  array('id_municipio' => '452','id_estado' => '23','municipio' => 'Machiques de Perijá'),
		  array('id_municipio' => '453','id_estado' => '23','municipio' => 'Mara'),
		  array('id_municipio' => '454','id_estado' => '23','municipio' => 'Maracaibo'),
		  array('id_municipio' => '455','id_estado' => '23','municipio' => 'Miranda'),
		  array('id_municipio' => '456','id_estado' => '23','municipio' => 'Rosario de Perijá'),
		  array('id_municipio' => '457','id_estado' => '23','municipio' => 'San Francisco'),
		  array('id_municipio' => '458','id_estado' => '23','municipio' => 'Santa Rita'),
		  array('id_municipio' => '459','id_estado' => '23','municipio' => 'Simón Bolívar'),
		  array('id_municipio' => '460','id_estado' => '23','municipio' => 'Sucre'),
		  array('id_municipio' => '461','id_estado' => '23','municipio' => 'Valmore Rodríguez'),
		  array('id_municipio' => '462','id_estado' => '24','municipio' => 'Libertador')
		);
        
        DB::table('municipios')->insert($municipios);
    }
}